cli: Few more cleanups for the DEA CLI
Indicate the enum class name in the argument name

Allow individual DEA to be redone with -redoAnalysis and deleted with
-deleteAnalysis.

Only write files to the standard location if they have been persisted to
the database. Otherwise, the user may specify a different location for
writing them.

Add expression data file options.

When results are not persisted, write them in the current directory
instead (or one set by -d).

Improve DEA config summary.

Allow redoing analysis of subsets using subset IDs with -redoSubset and
deleting them with -deleteSubset.

diff --git a/gemma-cli/src/main/config/bash_completion.d/gemma-cli b/gemma-cli/src/main/config/bash_completion.d/gemma-cli
--- a/gemma-cli/src/main/config/bash_completion.d/gemma-cli
+++ b/gemma-cli/src/main/config/bash_completion.d/gemma-cli
@@ -231,18 +231,18 @@ function __gemma_cli_complete() {
         fi
     fi
     if [[ " $words " =~ ' ubic.gemma.apps.DifferentialExpressionAnalysisCli ' ]]; then
-        if ! [[ "$current_option" =~ (--batch-format|--batch-output-file|--batch-report-frequency|--eeListfile|--excludeEEFile|--experiment|--experiment-set|--expressionQuery|--factors|--output-dir|--subset|--taxon|--type|-batchFormat|-batchOutputFile|-batchReportFrequency|-e|-eeset|-f|-factors|-mdate|-outputDir|-q|-subset|-t|-type|-x) ]]; then
-            mapfile -t -O "${#COMPREPLY[@]}" COMPREPLY < <(compgen -W "--batch-format --batch-output-file --batch-report-frequency --complete-factors --complete-subset-factors --delete --eeListfile --excludeEEFile --experiment --experiment-set --expressionQuery --factors --force --help --ignore-failing-subsets --no-bayes --no-db --no-files --output-dir --redo --subset --taxon --type --use-batch-factor -all -auto -batchFormat -batchOutputFile -batchReportFrequency -completeFactors -completeSubsetFactors -delete -e -eeset -f -factors -force -h -ignoreFailingSubsets -mdate -nobayes -nodb -nofiles -outputDir -q -redo -subset -t -type -usebatch -x" -- "$2")
+        if ! [[ "$current_option" =~ (--batch-format|--batch-output-file|--batch-report-frequency|--delete-analysis|--delete-subset|--eeListfile|--excludeEEFile|--experiment|--experiment-set|--expressionQuery|--factors|--output-dir|--redo-analysis|--redo-subset|--subset|--taxon|--type|-batchFormat|-batchOutputFile|-batchReportFrequency|-d|-deleteAnalysis|-deleteSubset|-e|-eeset|-f|-factors|-mdate|-q|-redoAnalysis|-redoSubset|-subset|-t|-type|-x) ]]; then
+            mapfile -t -O "${#COMPREPLY[@]}" COMPREPLY < <(compgen -W "--batch-format --batch-output-file --batch-report-frequency --complete-analyses --complete-factors --complete-subset-factors --complete-subsets --delete --delete-analysis --delete-subset --eeListfile --excludeEEFile --experiment --experiment-set --expressionQuery --factors --force --help --ignore-failing-subsets --no-bayes --no-db --no-files --output-dir --redo --redo-analysis --redo-subset --subset --taxon --type --use-batch-factor -all -auto -batchFormat -batchOutputFile -batchReportFrequency -completeAnalyses -completeFactors -completeSubsetFactors -completeSubsets -d -delete -deleteAnalysis -deleteSubset -e -eeset -f -factors -force -h -ignoreFailingSubsets -mdate -nobayes -nodb -nofiles -q -redo -redoAnalysis -redoSubset -subset -t -type -usebatch -x" -- "$2")
         fi
-        if [[ "$current_option" =~ (--batch-output-file|--eeListfile|--excludeEEFile|--output-dir|-batchOutputFile|-f|-outputDir|-x) ]]; then
+        if [[ "$current_option" =~ (--batch-output-file|--eeListfile|--excludeEEFile|--output-dir|-batchOutputFile|-d|-f|-x) ]]; then
             mapfile -t -O "${#COMPREPLY[@]}" COMPREPLY < <(compgen -f -- "$2")
         fi
     fi
     if [[ " $words " =~ ' diffExAnalyze ' ]]; then
-        if ! [[ "$current_option" =~ (--batch-format|--batch-output-file|--batch-report-frequency|--eeListfile|--excludeEEFile|--experiment|--experiment-set|--expressionQuery|--factors|--output-dir|--subset|--taxon|--type|-batchFormat|-batchOutputFile|-batchReportFrequency|-e|-eeset|-f|-factors|-mdate|-outputDir|-q|-subset|-t|-type|-x) ]]; then
-            mapfile -t -O "${#COMPREPLY[@]}" COMPREPLY < <(compgen -W "--batch-format --batch-output-file --batch-report-frequency --complete-factors --complete-subset-factors --delete --eeListfile --excludeEEFile --experiment --experiment-set --expressionQuery --factors --force --help --ignore-failing-subsets --no-bayes --no-db --no-files --output-dir --redo --subset --taxon --type --use-batch-factor -all -auto -batchFormat -batchOutputFile -batchReportFrequency -completeFactors -completeSubsetFactors -delete -e -eeset -f -factors -force -h -ignoreFailingSubsets -mdate -nobayes -nodb -nofiles -outputDir -q -redo -subset -t -type -usebatch -x" -- "$2")
+        if ! [[ "$current_option" =~ (--batch-format|--batch-output-file|--batch-report-frequency|--delete-analysis|--delete-subset|--eeListfile|--excludeEEFile|--experiment|--experiment-set|--expressionQuery|--factors|--output-dir|--redo-analysis|--redo-subset|--subset|--taxon|--type|-batchFormat|-batchOutputFile|-batchReportFrequency|-d|-deleteAnalysis|-deleteSubset|-e|-eeset|-f|-factors|-mdate|-q|-redoAnalysis|-redoSubset|-subset|-t|-type|-x) ]]; then
+            mapfile -t -O "${#COMPREPLY[@]}" COMPREPLY < <(compgen -W "--batch-format --batch-output-file --batch-report-frequency --complete-analyses --complete-factors --complete-subset-factors --complete-subsets --delete --delete-analysis --delete-subset --eeListfile --excludeEEFile --experiment --experiment-set --expressionQuery --factors --force --help --ignore-failing-subsets --no-bayes --no-db --no-files --output-dir --redo --redo-analysis --redo-subset --subset --taxon --type --use-batch-factor -all -auto -batchFormat -batchOutputFile -batchReportFrequency -completeAnalyses -completeFactors -completeSubsetFactors -completeSubsets -d -delete -deleteAnalysis -deleteSubset -e -eeset -f -factors -force -h -ignoreFailingSubsets -mdate -nobayes -nodb -nofiles -q -redo -redoAnalysis -redoSubset -subset -t -type -usebatch -x" -- "$2")
         fi
-        if [[ "$current_option" =~ (--batch-output-file|--eeListfile|--excludeEEFile|--output-dir|-batchOutputFile|-f|-outputDir|-x) ]]; then
+        if [[ "$current_option" =~ (--batch-output-file|--eeListfile|--excludeEEFile|--output-dir|-batchOutputFile|-d|-f|-x) ]]; then
             mapfile -t -O "${#COMPREPLY[@]}" COMPREPLY < <(compgen -f -- "$2")
         fi
     fi
