Single-cell work
Remove warning when excluding custom type as filterable properties

Use the same logic for detecting single-cell data and loading them into Gemma

Skip archives with too many skipped entries

Add a check after downloading to make sure that the resulting file has
the expected size.

Fix non-closed output stream when downloading a single file in a series.

Make sure that the output stream is closed before checking the resulting file size

Make characteristics and cellTypes collections immutable.

Add a denormalized NUMBER_OF_CHARACTERISTICS column to the
CELL_LEVEL_CHARACTERISTICS table.

Relocate validation of SCD in the DAO layer.

Use the Optional API for modelling preferred SCD, QT, etc.

diff --git a/gemma-cli/src/main/config/bash_completion.d/gemma-cli-staging b/gemma-cli/src/main/config/bash_completion.d/gemma-cli-staging
--- a/gemma-cli/src/main/config/bash_completion.d/gemma-cli-staging
+++ b/gemma-cli/src/main/config/bash_completion.d/gemma-cli-staging
@@ -217,18 +217,18 @@ function __gemma_cli_complete() {
         fi
     fi
     if [[ " $words " =~ ' ubic.gemma.core.apps.SingleCellDataLoaderCli ' ]]; then
-        if ! [[ "$current_option" =~ (--anndata-cell-type-factor-name|--anndata-sample-factor-name|--anndata-unknown-cell-type-indicator|--data-type|--eeListfile|--excludeEEFile|--experiment|--explicit-path|--expressionQuery|--platform|--taxon|-a|-annDataCellTypeFactorName|-annDataSampleFactorName|-annDataUnknownCellTypeIndicator|-batchFormat|-batchOutputFile|-dataType|-e|-eeset|-explicitPath|-f|-q|-t|-x) ]]; then
-            mapfile -t -O "${#COMPREPLY[@]}" COMPREPLY < <(compgen -W "--anndata-cell-type-factor-name --anndata-sample-factor-name --anndata-unknown-cell-type-indicator --cell-type-assignment-file --data-type --eeListfile --excludeEEFile --experiment --explicit-path --expressionQuery --help --platform --primary-cell-type-assignment --primary-qt --quantitation-type-name --replace --taxon -a -all -annDataCellTypeFactorName -annDataSampleFactorName -annDataUnknownCellTypeIndicator -batchFormat -batchOutputFile -cellTypeAssignmentFile -dataType -e -eeset -explicitPath -f -h -primaryCellTypeAssignment -primaryQt -q -quantitationTypeName -replace -t -x" -- "$2")
+        if ! [[ "$current_option" =~ (--anndata-cell-type-factor-name|--anndata-sample-factor-name|--anndata-unknown-cell-type-indicator|--cell-level-characteristics-file|--cell-type-assignment-file|--data-path|--data-type|--eeListfile|--excludeEEFile|--experiment|--expressionQuery|--platform|--quantitation-type-name|--taxon|-a|-annDataCellTypeFactorName|-annDataSampleFactorName|-annDataUnknownCellTypeIndicator|-batchFormat|-batchOutputFile|-clcFile|-ctaFile|-dataType|-e|-eeset|-f|-p|-q|-qtName|-t|-x) ]]; then
+            mapfile -t -O "${#COMPREPLY[@]}" COMPREPLY < <(compgen -W "--anndata-cell-type-factor-name --anndata-sample-factor-name --anndata-unknown-cell-type-indicator --cell-level-characteristics-file --cell-type-assignment-file --data-path --data-type --eeListfile --excludeEEFile --experiment --expressionQuery --help --load-cell-level-characteristics --load-cell-type-assignment --platform --preferred-cell-type-assignment --preferred-quantitation-type --quantitation-type-name --replace --taxon -a -all -annDataCellTypeFactorName -annDataSampleFactorName -annDataUnknownCellTypeIndicator -batchFormat -batchOutputFile -clcFile -ctaFile -dataType -e -eeset -f -h -loadClc -loadCta -p -preferredCta -preferredQt -q -qtName -replace -t -x" -- "$2")
         fi
-        if [[ "$current_option" =~ (--cell-type-assignment-file|--eeListfile|--excludeEEFile|-batchOutputFile|-cellTypeAssignmentFile|-f|-x) ]]; then
+        if [[ "$current_option" =~ (--cell-level-characteristics-file|--cell-type-assignment-file|--eeListfile|--excludeEEFile|-batchOutputFile|-clcFile|-ctaFile|-f|-x) ]]; then
             mapfile -t -O "${#COMPREPLY[@]}" COMPREPLY < <(compgen -f -- "$2")
         fi
     fi
     if [[ " $words " =~ ' loadSingleCellData ' ]]; then
-        if ! [[ "$current_option" =~ (--anndata-cell-type-factor-name|--anndata-sample-factor-name|--anndata-unknown-cell-type-indicator|--data-type|--eeListfile|--excludeEEFile|--experiment|--explicit-path|--expressionQuery|--platform|--taxon|-a|-annDataCellTypeFactorName|-annDataSampleFactorName|-annDataUnknownCellTypeIndicator|-batchFormat|-batchOutputFile|-dataType|-e|-eeset|-explicitPath|-f|-q|-t|-x) ]]; then
-            mapfile -t -O "${#COMPREPLY[@]}" COMPREPLY < <(compgen -W "--anndata-cell-type-factor-name --anndata-sample-factor-name --anndata-unknown-cell-type-indicator --cell-type-assignment-file --data-type --eeListfile --excludeEEFile --experiment --explicit-path --expressionQuery --help --platform --primary-cell-type-assignment --primary-qt --quantitation-type-name --replace --taxon -a -all -annDataCellTypeFactorName -annDataSampleFactorName -annDataUnknownCellTypeIndicator -batchFormat -batchOutputFile -cellTypeAssignmentFile -dataType -e -eeset -explicitPath -f -h -primaryCellTypeAssignment -primaryQt -q -quantitationTypeName -replace -t -x" -- "$2")
+        if ! [[ "$current_option" =~ (--anndata-cell-type-factor-name|--anndata-sample-factor-name|--anndata-unknown-cell-type-indicator|--cell-level-characteristics-file|--cell-type-assignment-file|--data-path|--data-type|--eeListfile|--excludeEEFile|--experiment|--expressionQuery|--platform|--quantitation-type-name|--taxon|-a|-annDataCellTypeFactorName|-annDataSampleFactorName|-annDataUnknownCellTypeIndicator|-batchFormat|-batchOutputFile|-clcFile|-ctaFile|-dataType|-e|-eeset|-f|-p|-q|-qtName|-t|-x) ]]; then
+            mapfile -t -O "${#COMPREPLY[@]}" COMPREPLY < <(compgen -W "--anndata-cell-type-factor-name --anndata-sample-factor-name --anndata-unknown-cell-type-indicator --cell-level-characteristics-file --cell-type-assignment-file --data-path --data-type --eeListfile --excludeEEFile --experiment --expressionQuery --help --load-cell-level-characteristics --load-cell-type-assignment --platform --preferred-cell-type-assignment --preferred-quantitation-type --quantitation-type-name --replace --taxon -a -all -annDataCellTypeFactorName -annDataSampleFactorName -annDataUnknownCellTypeIndicator -batchFormat -batchOutputFile -clcFile -ctaFile -dataType -e -eeset -f -h -loadClc -loadCta -p -preferredCta -preferredQt -q -qtName -replace -t -x" -- "$2")
         fi
-        if [[ "$current_option" =~ (--cell-type-assignment-file|--eeListfile|--excludeEEFile|-batchOutputFile|-cellTypeAssignmentFile|-f|-x) ]]; then
+        if [[ "$current_option" =~ (--cell-level-characteristics-file|--cell-type-assignment-file|--eeListfile|--excludeEEFile|-batchOutputFile|-clcFile|-ctaFile|-f|-x) ]]; then
             mapfile -t -O "${#COMPREPLY[@]}" COMPREPLY < <(compgen -f -- "$2")
         fi
     fi
@@ -905,18 +905,18 @@ function __gemma_cli_complete() {
         fi
     fi
     if [[ " $words " =~ ' ubic.gemma.core.apps.SingleCellDataDownloaderCli ' ]]; then
-        if ! [[ "$current_option" =~ (--acc|--data-type|--fetch-threads|--file|--mex-barcodes-file|--mex-features-file|--mex-matrix-file|--retry|--sample-accessions|--summary-output-file|--supplementary-file|--threads|-dataType|-e|-f|-fetchThreads|-mexBarcodesFile|-mexFeaturesFile|-mexMatrixFile|-retry|-s|-sampleAccessions|-supplementaryFile|-threads) ]]; then
-            mapfile -t -O "${#COMPREPLY[@]}" COMPREPLY < <(compgen -W "--acc --data-type --fetch-threads --file --help --mex-barcodes-file --mex-features-file --mex-matrix-file --resume --retry --sample-accessions --summary-output-file --supplementary-file --threads -dataType -e -f -fetchThreads -h -mexBarcodesFile -mexFeaturesFile -mexMatrixFile -r -retry -s -sampleAccessions -supplementaryFile -threads" -- "$2")
+        if ! [[ "$current_option" =~ (--acc|--data-type|--fetch-threads|--file|--mex-barcodes-file|--mex-features-file|--mex-matrix-file|--retry|--sample-accessions|--summary-output-file|--supplementary-file|--threads|-batchFormat|-batchOutputFile|-dataType|-e|-f|-fetchThreads|-mexBarcodesFile|-mexFeaturesFile|-mexMatrixFile|-retry|-s|-sampleAccessions|-supplementaryFile|-threads) ]]; then
+            mapfile -t -O "${#COMPREPLY[@]}" COMPREPLY < <(compgen -W "--acc --data-type --fetch-threads --file --help --mex-barcodes-file --mex-features-file --mex-matrix-file --resume --retry --sample-accessions --summary-output-file --supplementary-file --threads -batchFormat -batchOutputFile -dataType -e -f -fetchThreads -h -mexBarcodesFile -mexFeaturesFile -mexMatrixFile -r -retry -s -sampleAccessions -supplementaryFile -threads" -- "$2")
         fi
-        if [[ "$current_option" =~ (--file|--mex-barcodes-file|--mex-features-file|--mex-matrix-file|--summary-output-file|--supplementary-file|-f|-mexBarcodesFile|-mexFeaturesFile|-mexMatrixFile|-s|-supplementaryFile) ]]; then
+        if [[ "$current_option" =~ (--file|--mex-barcodes-file|--mex-features-file|--mex-matrix-file|--summary-output-file|--supplementary-file|-batchOutputFile|-f|-mexBarcodesFile|-mexFeaturesFile|-mexMatrixFile|-s|-supplementaryFile) ]]; then
             mapfile -t -O "${#COMPREPLY[@]}" COMPREPLY < <(compgen -f -- "$2")
         fi
     fi
     if [[ " $words " =~ ' downloadSingleCellData ' ]]; then
-        if ! [[ "$current_option" =~ (--acc|--data-type|--fetch-threads|--file|--mex-barcodes-file|--mex-features-file|--mex-matrix-file|--retry|--sample-accessions|--summary-output-file|--supplementary-file|--threads|-dataType|-e|-f|-fetchThreads|-mexBarcodesFile|-mexFeaturesFile|-mexMatrixFile|-retry|-s|-sampleAccessions|-supplementaryFile|-threads) ]]; then
-            mapfile -t -O "${#COMPREPLY[@]}" COMPREPLY < <(compgen -W "--acc --data-type --fetch-threads --file --help --mex-barcodes-file --mex-features-file --mex-matrix-file --resume --retry --sample-accessions --summary-output-file --supplementary-file --threads -dataType -e -f -fetchThreads -h -mexBarcodesFile -mexFeaturesFile -mexMatrixFile -r -retry -s -sampleAccessions -supplementaryFile -threads" -- "$2")
+        if ! [[ "$current_option" =~ (--acc|--data-type|--fetch-threads|--file|--mex-barcodes-file|--mex-features-file|--mex-matrix-file|--retry|--sample-accessions|--summary-output-file|--supplementary-file|--threads|-batchFormat|-batchOutputFile|-dataType|-e|-f|-fetchThreads|-mexBarcodesFile|-mexFeaturesFile|-mexMatrixFile|-retry|-s|-sampleAccessions|-supplementaryFile|-threads) ]]; then
+            mapfile -t -O "${#COMPREPLY[@]}" COMPREPLY < <(compgen -W "--acc --data-type --fetch-threads --file --help --mex-barcodes-file --mex-features-file --mex-matrix-file --resume --retry --sample-accessions --summary-output-file --supplementary-file --threads -batchFormat -batchOutputFile -dataType -e -f -fetchThreads -h -mexBarcodesFile -mexFeaturesFile -mexMatrixFile -r -retry -s -sampleAccessions -supplementaryFile -threads" -- "$2")
         fi
-        if [[ "$current_option" =~ (--file|--mex-barcodes-file|--mex-features-file|--mex-matrix-file|--summary-output-file|--supplementary-file|-f|-mexBarcodesFile|-mexFeaturesFile|-mexMatrixFile|-s|-supplementaryFile) ]]; then
+        if [[ "$current_option" =~ (--file|--mex-barcodes-file|--mex-features-file|--mex-matrix-file|--summary-output-file|--supplementary-file|-batchOutputFile|-f|-mexBarcodesFile|-mexFeaturesFile|-mexMatrixFile|-s|-supplementaryFile) ]]; then
             mapfile -t -O "${#COMPREPLY[@]}" COMPREPLY < <(compgen -f -- "$2")
         fi
     fi
