Limit assays types in CELLxGENE tests
Tests were failing because we've added many new assay types.

diff --git a/gemma-cli/src/main/config/bash_completion.d/gemma-cli-staging b/gemma-cli/src/main/config/bash_completion.d/gemma-cli-staging
--- a/gemma-cli/src/main/config/bash_completion.d/gemma-cli-staging
+++ b/gemma-cli/src/main/config/bash_completion.d/gemma-cli-staging
@@ -256,16 +256,16 @@ function __gemma_cli_staging_complete() {
         fi
     fi
     if [[ " $words " =~ ' ubic.gemma.apps.SingleCellDataDownloaderCli ' ]]; then
-        if ! [[ "$current_option" =~ (--acc|--batch-format|--batch-output-file|--batch-report-frequency|--cellxgene-asset-id|--cellxgene-collection-id|--cellxgene-dataset-id|--data-type|--fetch-threads|--file|--mex-barcodes-file|--mex-features-file|--mex-matrix-file|--retry|--retry-count|--sample-accessions|--summary-output-file|--supplementary-file|--threads|-batchFormat|-batchOutputFile|-batchReportFrequency|-cellxgeneAssetId|-cellxgeneCollectionId|-cellxgeneDatasetId|-dataType|-e|-f|-fetchThreads|-mexBarcodesFile|-mexFeaturesFile|-mexMatrixFile|-retry|-retryCount|-s|-sampleAccessions|-supplementaryFile|-threads) ]]; then
-            mapfile -t -O "${#COMPREPLY[@]}" COMPREPLY < <(compgen -W "--acc --batch-format --batch-output-file --batch-report-frequency --cellxgene --cellxgene-all-datasets --cellxgene-asset-id --cellxgene-collection-id --cellxgene-dataset-id --data-type --fetch-threads --file --help --mex-barcodes-file --mex-features-file --mex-matrix-file --resume --resume-ignore-unknown-datasets --retry --retry-count --sample-accessions --skip-download --summary-output-file --supplementary-file --threads -batchFormat -batchOutputFile -batchReportFrequency -cellxgene -cellxgeneAllDatasets -cellxgeneAssetId -cellxgeneCollectionId -cellxgeneDatasetId -dataType -e -f -fetchThreads -h -mexBarcodesFile -mexFeaturesFile -mexMatrixFile -r -resumeIgnoreUnknownDatasets -retry -retryCount -s -sampleAccessions -skipDownload -supplementaryFile -threads" -- "$2")
+        if ! [[ "$current_option" =~ (--acc|--batch-format|--batch-output-file|--batch-report-frequency|--cellxgene-assays|--cellxgene-asset-id|--cellxgene-collection-id|--cellxgene-dataset-id|--data-type|--fetch-threads|--file|--mex-barcodes-file|--mex-features-file|--mex-matrix-file|--retry|--retry-count|--sample-accessions|--summary-output-file|--supplementary-file|--threads|-batchFormat|-batchOutputFile|-batchReportFrequency|-cellxgeneAssays|-cellxgeneAssetId|-cellxgeneCollectionId|-cellxgeneDatasetId|-dataType|-e|-f|-fetchThreads|-mexBarcodesFile|-mexFeaturesFile|-mexMatrixFile|-retry|-retryCount|-s|-sampleAccessions|-supplementaryFile|-threads) ]]; then
+            mapfile -t -O "${#COMPREPLY[@]}" COMPREPLY < <(compgen -W "--acc --batch-format --batch-output-file --batch-report-frequency --cellxgene --cellxgene-all-datasets --cellxgene-assays --cellxgene-asset-id --cellxgene-collection-id --cellxgene-dataset-id --data-type --fetch-threads --file --help --mex-barcodes-file --mex-features-file --mex-matrix-file --resume --resume-ignore-unknown-datasets --retry --retry-count --sample-accessions --skip-download --summary-output-file --supplementary-file --threads -batchFormat -batchOutputFile -batchReportFrequency -cellxgene -cellxgeneAllDatasets -cellxgeneAssays -cellxgeneAssetId -cellxgeneCollectionId -cellxgeneDatasetId -dataType -e -f -fetchThreads -h -mexBarcodesFile -mexFeaturesFile -mexMatrixFile -r -resumeIgnoreUnknownDatasets -retry -retryCount -s -sampleAccessions -skipDownload -supplementaryFile -threads" -- "$2")
         fi
         if [[ "$current_option" =~ (--batch-output-file|--file|--summary-output-file|-batchOutputFile|-f|-s) ]]; then
             mapfile -t -O "${#COMPREPLY[@]}" COMPREPLY < <(compgen -f -- "$2")
         fi
     fi
     if [[ " $words " =~ ' downloadSingleCellData ' ]]; then
-        if ! [[ "$current_option" =~ (--acc|--batch-format|--batch-output-file|--batch-report-frequency|--cellxgene-asset-id|--cellxgene-collection-id|--cellxgene-dataset-id|--data-type|--fetch-threads|--file|--mex-barcodes-file|--mex-features-file|--mex-matrix-file|--retry|--retry-count|--sample-accessions|--summary-output-file|--supplementary-file|--threads|-batchFormat|-batchOutputFile|-batchReportFrequency|-cellxgeneAssetId|-cellxgeneCollectionId|-cellxgeneDatasetId|-dataType|-e|-f|-fetchThreads|-mexBarcodesFile|-mexFeaturesFile|-mexMatrixFile|-retry|-retryCount|-s|-sampleAccessions|-supplementaryFile|-threads) ]]; then
-            mapfile -t -O "${#COMPREPLY[@]}" COMPREPLY < <(compgen -W "--acc --batch-format --batch-output-file --batch-report-frequency --cellxgene --cellxgene-all-datasets --cellxgene-asset-id --cellxgene-collection-id --cellxgene-dataset-id --data-type --fetch-threads --file --help --mex-barcodes-file --mex-features-file --mex-matrix-file --resume --resume-ignore-unknown-datasets --retry --retry-count --sample-accessions --skip-download --summary-output-file --supplementary-file --threads -batchFormat -batchOutputFile -batchReportFrequency -cellxgene -cellxgeneAllDatasets -cellxgeneAssetId -cellxgeneCollectionId -cellxgeneDatasetId -dataType -e -f -fetchThreads -h -mexBarcodesFile -mexFeaturesFile -mexMatrixFile -r -resumeIgnoreUnknownDatasets -retry -retryCount -s -sampleAccessions -skipDownload -supplementaryFile -threads" -- "$2")
+        if ! [[ "$current_option" =~ (--acc|--batch-format|--batch-output-file|--batch-report-frequency|--cellxgene-assays|--cellxgene-asset-id|--cellxgene-collection-id|--cellxgene-dataset-id|--data-type|--fetch-threads|--file|--mex-barcodes-file|--mex-features-file|--mex-matrix-file|--retry|--retry-count|--sample-accessions|--summary-output-file|--supplementary-file|--threads|-batchFormat|-batchOutputFile|-batchReportFrequency|-cellxgeneAssays|-cellxgeneAssetId|-cellxgeneCollectionId|-cellxgeneDatasetId|-dataType|-e|-f|-fetchThreads|-mexBarcodesFile|-mexFeaturesFile|-mexMatrixFile|-retry|-retryCount|-s|-sampleAccessions|-supplementaryFile|-threads) ]]; then
+            mapfile -t -O "${#COMPREPLY[@]}" COMPREPLY < <(compgen -W "--acc --batch-format --batch-output-file --batch-report-frequency --cellxgene --cellxgene-all-datasets --cellxgene-assays --cellxgene-asset-id --cellxgene-collection-id --cellxgene-dataset-id --data-type --fetch-threads --file --help --mex-barcodes-file --mex-features-file --mex-matrix-file --resume --resume-ignore-unknown-datasets --retry --retry-count --sample-accessions --skip-download --summary-output-file --supplementary-file --threads -batchFormat -batchOutputFile -batchReportFrequency -cellxgene -cellxgeneAllDatasets -cellxgeneAssays -cellxgeneAssetId -cellxgeneCollectionId -cellxgeneDatasetId -dataType -e -f -fetchThreads -h -mexBarcodesFile -mexFeaturesFile -mexMatrixFile -r -resumeIgnoreUnknownDatasets -retry -retryCount -s -sampleAccessions -skipDownload -supplementaryFile -threads" -- "$2")
         fi
         if [[ "$current_option" =~ (--batch-output-file|--file|--summary-output-file|-batchOutputFile|-f|-s) ]]; then
             mapfile -t -O "${#COMPREPLY[@]}" COMPREPLY < <(compgen -f -- "$2")
@@ -1234,13 +1234,13 @@ function __gemma_cli_staging_complete() {
         mapfile -t -O "${#COMPREPLY[@]}" COMPREPLY < <(compgen -W "--force --help -force -h -o" -- "$2")
     fi
     if [[ " $words " =~ ' ubic.gemma.apps.CellXGeneGrabberCli ' ]]; then
-        if ! [[ "$current_option" =~ (--allowed-taxa|-allowedTaxa) ]]; then
-            mapfile -t -O "${#COMPREPLY[@]}" COMPREPLY < <(compgen -W "--allowed-taxa --help -allowedTaxa -h" -- "$2")
+        if ! [[ "$current_option" =~ (--allowed-taxa|--assays|-allowedTaxa|-assays) ]]; then
+            mapfile -t -O "${#COMPREPLY[@]}" COMPREPLY < <(compgen -W "--allowed-taxa --assays --help -allowedTaxa -assays -h" -- "$2")
         fi
     fi
     if [[ " $words " =~ ' listCELLxGENEData ' ]]; then
-        if ! [[ "$current_option" =~ (--allowed-taxa|-allowedTaxa) ]]; then
-            mapfile -t -O "${#COMPREPLY[@]}" COMPREPLY < <(compgen -W "--allowed-taxa --help -allowedTaxa -h" -- "$2")
+        if ! [[ "$current_option" =~ (--allowed-taxa|--assays|-allowedTaxa|-assays) ]]; then
+            mapfile -t -O "${#COMPREPLY[@]}" COMPREPLY < <(compgen -W "--allowed-taxa --assays --help -allowedTaxa -assays -h" -- "$2")
         fi
     fi
     if [[ " $words " =~ ' ubic.gemma.apps.ExternalDatabaseOverviewCli ' ]]; then
