Update completion scripts

diff --git a/gemma-cli/src/main/config/bash_completion.d/gemma-cli b/gemma-cli/src/main/config/bash_completion.d/gemma-cli
--- a/gemma-cli/src/main/config/bash_completion.d/gemma-cli
+++ b/gemma-cli/src/main/config/bash_completion.d/gemma-cli
@@ -2,11 +2,11 @@ function __gemma_cli_complete() {
     COMPREPLY=()
     words="${COMP_WORDS[*]}"
     current_option="${COMP_WORDS[$COMP_CWORD-1]}"
-    if ! [[ " $words " =~ ' '(affyFromCel|pubmedSearchAndSave|gwasDownload|migrateFactorValues|makePlatformAnnotFiles|platformSubsumptionTest|listExternalDatabases|printExperimentalDesign|mergePlatforms|pubmedLoad|getDataMatrix|findObsoleteTerms|vectorMerge|generateDataFile|loadTaxa|rnaseqBatchInfo|platformMapSummary|loadGenesFromFile|dgaDownload|mapPlatformToGenes|searchIndex|probeRename|pubmedAssociateToExperiments|makePrivate|addGEOData|updateExternalDatabase|splitExperiment|updateEe2c|importDesign|makeProcessedData|affyCollapse|deletePlatformElements|diffExAnalyze|omimDownload|geneUpdate|makePublic|deleteExperiments|detachSequences|dumpForNIF|updateMultifunc|deletePhenotypes|sfariDownload|platformRepeatScan|addTSVData|pca|updateGOAnnots|ctdDownload|viewExpDesigns|affyAltsUpdate|blackList|deleteDiffEx|fillBatchInfo|genericPlatform|orderVectorsByDesign|adATcleanup|replaceData|rgdDownload|runGeeq|rnaseqDataAdd|seqCleanup|listGEOData|fetchMeshTerms|evidenceImport|switchExperimentPlatform|addPlatformSequences|coexpAnalyze|blatPlatform|corrMat|updatePubMeds|loadEvidenceForClassifier|findDatasetPubs|addExternalDatabase)' ' ]]; then
+    if ! [[ " $words " =~ ' '(affyFromCel|pubmedSearchAndSave|gwasDownload|migrateFactorValues|makePlatformAnnotFiles|platformSubsumptionTest|listExternalDatabases|printExperimentalDesign|mergePlatforms|pubmedLoad|getDataMatrix|findObsoleteTerms|vectorMerge|generateDataFile|loadTaxa|rnaseqBatchInfo|platformMapSummary|loadGenesFromFile|dgaDownload|mapPlatformToGenes|searchIndex|probeRename|pubmedAssociateToExperiments|makePrivate|addGEOData|updateExternalDatabase|splitExperiment|updateEe2c|importDesign|makeProcessedData|affyCollapse|deletePlatformElements|diffExAnalyze|omimDownload|geneUpdate|refreshExperiment|makePublic|deleteExperiments|detachSequences|dumpForNIF|updateMultifunc|deletePhenotypes|sfariDownload|platformRepeatScan|addTSVData|pca|updateGOAnnots|ctdDownload|viewExpDesigns|affyAltsUpdate|blackList|deleteDiffEx|fillBatchInfo|genericPlatform|orderVectorsByDesign|adATcleanup|replaceData|rgdDownload|runGeeq|rnaseqDataAdd|seqCleanup|listGEOData|fetchMeshTerms|evidenceImport|switchExperimentPlatform|addPlatformSequences|coexpAnalyze|blatPlatform|corrMat|updatePubMeds|loadEvidenceForClassifier|findDatasetPubs|addExternalDatabase)' ' ]]; then
         if ! [[ "$current_option" =~ (--logger|-v|--verbosity|-cs|--completion-shell|-logger) ]]; then
             mapfile -t -O "${#COMPREPLY[@]}" COMPREPLY < <(compgen -W "'-version' '-ha' '--version' '-v' '--completion-shell' '-logger' '-testdb' '--help' '--testdb' '--logger' '-c' '--completion' '--verbosity' '-h' '-cs' '--help-all'" -- "$2")
         fi
-        mapfile -t -O "${#COMPREPLY[@]}" COMPREPLY < <(compgen -W "'affyFromCel' 'pubmedSearchAndSave' 'gwasDownload' 'migrateFactorValues' 'makePlatformAnnotFiles' 'platformSubsumptionTest' 'listExternalDatabases' 'printExperimentalDesign' 'mergePlatforms' 'pubmedLoad' 'getDataMatrix' 'findObsoleteTerms' 'vectorMerge' 'generateDataFile' 'loadTaxa' 'rnaseqBatchInfo' 'platformMapSummary' 'loadGenesFromFile' 'dgaDownload' 'mapPlatformToGenes' 'searchIndex' 'probeRename' 'pubmedAssociateToExperiments' 'makePrivate' 'addGEOData' 'updateExternalDatabase' 'splitExperiment' 'updateEe2c' 'importDesign' 'makeProcessedData' 'affyCollapse' 'deletePlatformElements' 'diffExAnalyze' 'omimDownload' 'geneUpdate' 'makePublic' 'deleteExperiments' 'detachSequences' 'dumpForNIF' 'updateMultifunc' 'deletePhenotypes' 'sfariDownload' 'platformRepeatScan' 'addTSVData' 'pca' 'updateGOAnnots' 'ctdDownload' 'viewExpDesigns' 'affyAltsUpdate' 'blackList' 'deleteDiffEx' 'fillBatchInfo' 'genericPlatform' 'orderVectorsByDesign' 'adATcleanup' 'replaceData' 'rgdDownload' 'runGeeq' 'rnaseqDataAdd' 'seqCleanup' 'listGEOData' 'fetchMeshTerms' 'evidenceImport' 'switchExperimentPlatform' 'addPlatformSequences' 'coexpAnalyze' 'blatPlatform' 'corrMat' 'updatePubMeds' 'loadEvidenceForClassifier' 'findDatasetPubs' 'addExternalDatabase'" -- "$2")
+        mapfile -t -O "${#COMPREPLY[@]}" COMPREPLY < <(compgen -W "'affyFromCel' 'pubmedSearchAndSave' 'gwasDownload' 'migrateFactorValues' 'makePlatformAnnotFiles' 'platformSubsumptionTest' 'listExternalDatabases' 'printExperimentalDesign' 'mergePlatforms' 'pubmedLoad' 'getDataMatrix' 'findObsoleteTerms' 'vectorMerge' 'generateDataFile' 'loadTaxa' 'rnaseqBatchInfo' 'platformMapSummary' 'loadGenesFromFile' 'dgaDownload' 'mapPlatformToGenes' 'searchIndex' 'probeRename' 'pubmedAssociateToExperiments' 'makePrivate' 'addGEOData' 'updateExternalDatabase' 'splitExperiment' 'updateEe2c' 'importDesign' 'makeProcessedData' 'affyCollapse' 'deletePlatformElements' 'diffExAnalyze' 'omimDownload' 'geneUpdate' 'refreshExperiment' 'makePublic' 'deleteExperiments' 'detachSequences' 'dumpForNIF' 'updateMultifunc' 'deletePhenotypes' 'sfariDownload' 'platformRepeatScan' 'addTSVData' 'pca' 'updateGOAnnots' 'ctdDownload' 'viewExpDesigns' 'affyAltsUpdate' 'blackList' 'deleteDiffEx' 'fillBatchInfo' 'genericPlatform' 'orderVectorsByDesign' 'adATcleanup' 'replaceData' 'rgdDownload' 'runGeeq' 'rnaseqDataAdd' 'seqCleanup' 'listGEOData' 'fetchMeshTerms' 'evidenceImport' 'switchExperimentPlatform' 'addPlatformSequences' 'coexpAnalyze' 'blatPlatform' 'corrMat' 'updatePubMeds' 'loadEvidenceForClassifier' 'findDatasetPubs' 'addExternalDatabase'" -- "$2")
     fi
     if [[ " $words " =~ ' addGEOData ' ]]; then
         if ! [[ "$current_option" =~ (-softfile|--acc|--file|-e|-f|-batchFormat|-batchOutputFile) ]]; then
@@ -157,6 +157,14 @@ function __gemma_cli_complete() {
             mapfile -t -O "${#COMPREPLY[@]}" COMPREPLY < <(compgen -W "'-all' '--eeListfile' '-q' '-force' '-t' '--experiment' '-x' '--expressionQuery' '-pubmedIDFile' '-batchOutputFile' '--help' '-e' '-f' '--taxon' '--excludeEEFile' '-batchFormat' '-h' '-eeset' '--force'" -- "$2")
         fi
         if [[ "$current_option" =~ (--eeListfile|-f|--excludeEEFile|-x|-pubmedIDFile|-batchOutputFile) ]]; then
+            mapfile -t -O "${#COMPREPLY[@]}" COMPREPLY < <(compgen -f -- "$2")
+        fi
+    fi
+    if [[ " $words " =~ ' refreshExperiment ' ]]; then
+        if ! [[ "$current_option" =~ (--eeListfile|-q|-t|-threads|--experiment|-x|--expressionQuery|-batchOutputFile|-e|-f|--taxon|--excludeEEFile|-batchFormat|-eeset) ]]; then
+            mapfile -t -O "${#COMPREPLY[@]}" COMPREPLY < <(compgen -W "'-all' '--eeListfile' '-q' '-t' '-threads' '--experiment' '-x' '--expressionQuery' '-batchOutputFile' '--help' '-e' '-f' '--taxon' '--excludeEEFile' '-batchFormat' '-h' '-eeset'" -- "$2")
+        fi
+        if [[ "$current_option" =~ (--eeListfile|-f|--excludeEEFile|-x|-batchOutputFile) ]]; then
             mapfile -t -O "${#COMPREPLY[@]}" COMPREPLY < <(compgen -f -- "$2")
         fi
     fi
